name: release

on: push

jobs:
  upload-plugin-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: "5.1.5"

    - uses: leafo/gh-actions-luarocks@v2

    - name: build
      run: |
        cd build-image
        ./build.sh
    
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: mascarenhas
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: push
      run: |
        docker tag kong-oidc:2.0 docker.pkg.github.com/mascarenhas/kong-oidc/kong-oidc:2.0
        docker push docker.pkg.github.com/mascarenhas/kong-oidc/kong-oidc:2.0
